services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - CLIENT_URL=http://localhost:5174
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "5174:5174"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
