services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - CLIENT_URL=http://54.210.207.82:5174
      - NODE_ENV=production
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build: 
      context: ./frontend
      args:
        - VITE_API_URL=http://54.210.207.82:5000
    ports:
      - "5174:5174"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
